name: Daily Data Update

on:
  schedule:
    - cron: '*/3 * * * *'  # Every 3 minutes
  workflow_dispatch:       # Allows you to trigger it manually from GitHub

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ Enables pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        run: git status
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python update script
        run: python scripts/update_json.py

      - name: Commit and push updated data.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/data.json
          git commit -m "Automated daily update" || echo "No changes to commit"
          git push
